// experiments/reactjs/backoffice/src/components/Sidebar.jsx
import React from 'react';
import { Nav } from 'react-bootstrap';
import { Link, useLocation } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';

const Sidebar = () => {
    const { logout } = useAuth();
    const location = useLocation();

    const isActive = (path) => location.pathname === path;

    return (
        <div className="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style={{ width: '280px', minHeight: '100vh' }}>
            <div className="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                <span className="fs-4">MES Backoffice</span>
            </div>
            <hr />
            <Nav className="flex-column mb-auto">
                <Nav.Item>
                    <Link to="/dashboard" className={`nav-link text-white ${isActive('/dashboard') ? 'active bg-primary' : ''}`}>
                        Dashboard
                    </Link>
                </Nav.Item>

                <div className="mt-3 text-muted text-uppercase small">Factory Assets</div>
                <Nav.Item>
                    <Link to="/machines" className={`nav-link text-white ${isActive('/machines') ? 'active bg-primary' : ''}`}>
                        Machines
                    </Link>
                </Nav.Item>

                 <div className="mt-3 text-muted text-uppercase small">Master Data</div>
                <Nav.Item>
                    <Link to="/articles" className={`nav-link text-white ${isActive('/articles') ? 'active bg-primary' : ''}`}>
                        Articles
                    </Link>
                </Nav.Item>
            </Nav>
            <hr />
            <button onClick={logout} className="btn btn-outline-light w-100">Log Out</button>
        </div>
    );
};

export default Sidebar;

// experiments/angular/backoffice/src/app/shared/components/sidebar/sidebar.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `
    <div class="sidebar d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 280px; height: 100vh; position: fixed; top: 0; left: 0;">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <i class="fa-solid fa-industry me-2"></i>
        <span class="fs-4">MES Backoffice</span>
      </a>
      <hr>
      <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
          <a routerLink="/dashboard" routerLinkActive="active" class="nav-link text-white">
            <i class="fa-solid fa-gauge-high me-2"></i>
            Dashboard
          </a>
        </li>
        <li class="nav-item">
          <a routerLink="/users" routerLinkActive="active" class="nav-link text-white">
            <i class="fa-solid fa-users me-2"></i>
            Users
          </a>
        </li>
      </ul>
      <hr>
      <div class="dropdown">
        <a href="#" class="d-flex align-items-center text-white text-decoration-none" (click)="logout($event)">
           <i class="fa-solid fa-right-from-bracket me-2"></i>
           <strong>Sign out</strong>
        </a>
      </div>
    </div>
  `,
  styles: [`
    .nav-link.active {
      background-color: #0d6efd;
    }
    .nav-link:not(.active):hover {
        background-color: rgba(255,255,255,0.1);
    }
  `]
})
export class SidebarComponent {
  constructor(public authService: AuthService) {}

  logout(event: Event) {
    event.preventDefault();
    this.authService.logout();
  }
}
